<?php

namespace AppBundle\Repository;

/**
 * HealthCareRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HealthCareRepository extends \Doctrine\ORM\EntityRepository
{
}
