<?php

namespace AppBundle\Repository;

/**
 * HealthSessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HealthSessionRepository extends \Doctrine\ORM\EntityRepository
{
}
